SELECT ENAME, SALARY, COMMISSION,
    NVL(COMMISSION, 0),
    SALARY*12+NVL(COMMISSION, 0)
FROM EMPLOYEE
ORDER BY JOB;    

SELECT ENAME, SALARY, COMMISSION,
    NVL2(COMMISSION, SALARY * 12 + COMMISSION, SALARY * 12) 
--NVL2(expr1, expr2, expr3) : expr1이 null이 아니면 expr2 반환, null이면 expr3 반환
FROM EMPLOYEE
ORDER BY JOB;